apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metrics-ip-enrichment.fullname" . }}-mmdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metrics-ip-enrichment.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mmdb.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mmdb.pvc.size }}
  {{- if .Values.mmdb.pvc.storageClass }}
  storageClassName: {{ .Values.mmdb.pvc.storageClass }}
  {{- end }}
